demo-data:
  exams:
    - examNr: 6
      examName: Wahlfach
      date: 07.06.2020
      writeExam: 6
  users:
    - matNr: 123456
      email: derdoktor48@web.de
      userName: rotkodr3d
      password: 123
      examsToWrite: 6
  exercises:
    - id: 1
      type: Hausarbeit
      timeNeed: 20
      timeWorked: 15
      deadline: 07.06.2020
      exerciseForExam: 6
      student: 123456
  learn-units:
  