spring:
  profiles:    include:    - lifecycle
  jpa:
    hibernate:
      ddl-auto: update #update #create-drop, none, validate, update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lernix?serverTimezone=UTC
    username: root
    password: 

logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace