demo-data:
  exams:
    - examNr: 6
      examName: Wahlfach
      date: 07.06.2020
      learningTimeNeed: 100
      writeExam: 6
    - examNr: 7
      examName: Finanzierung und Investitionen
      date: 07.06.2020
      learningTimeNeed: 120
      writeExam: 6
    - examNr: 8
      examName: Fortgeschrittene Programmierung
      date: 10.06.2020
      learningTimeNeed: 80
      writeExam: 6
  users:
    - matNr: 123456
      email: derdoktor48@web.de
      userName: rotkodr3d
      password: $2a$10$.AIHN1W1X3pIrSsow7Yh0.DpyM93sSZaAeni5ZiMYLUL6hxktb.T2
      examsToWrite: 6, 7
    - matNr: 112233
      email: email@email.de
      userName: name
      password: $2a$10$8xoNd9Ylj3icH4n2JauR/.GICZ8oQXaCDjeqCzYZx9HRlj8Y.wzVq
      examsToWrite: 6
  exercises:
    - id: 1
      type: Hausarbeit
      timeNeed: 20
      timeWorked: 15
      deadline: 15.06.2020
      exerciseForExam: 6
      student: 123456
    - id: 2
      type: Projekt
      timeNeed: 30
      timeWorked: 22
      deadline: 07.06.2020
      exerciseForExam: 6
      student: 123456
    - id: 3
      type: Projekt
      timeNeed: 30
      timeWorked: 22
      deadline: 07.06.2020
      exerciseForExam: 6
      student: 112233
